replicaCount: 1

image:
  repository: python
  tag: "3.10-slim"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources: {}


config:
  time_config:
    training_hours: 12
    forecast_hours: 1
    step_size: 60
    min_data_points: 100
  metrics_queries:
    node_cpu_usage: "sum(rate(node_cpu_seconds_total{mode!='idle'}[1m]))"
    cpu_load: "sum(node_load5)"
    node_active_memory_usage: "sum(node_memory_Active_bytes / node_memory_MemTotal_bytes)"
    node_available_memory_gb: "sum(node_memory_MemAvailable_bytes) / (1024 * 1024 * 1024)"
    node_disk_read_mb: "sum(rate(node_disk_read_bytes_total[1m])) / (1024 * 1024 )"
    node_disk_write_mb: "sum(rate(node_disk_write_bytes_total[1m])) / (1024 * 1024 )"
    node_root_disk_usage_gb: "sum(node_filesystem_avail_bytes{mountpoint='/'}/(1024*1024*1024))"
