apiVersion: v1
kind: Service
metadata:
  name: prophet-svc 
  labels:
    app: prophet 
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prophet 

