apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prophet-service-monitor 
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  selector:
    matchLabels:
      app: prophet
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 10s

